#baseurl = "https://mespadoto.github.io/"
title = "A Quantitative Survey of Multidimensional Projection Techniques"
author = "M. Espadoto"
paginate = 4
theme = "arabica"
publishDir = "../docs"

[params]
    description = "Mateus Espadoto, Rafael M. Martins, Andreas Kerren, Nina S. T. Hirata and Alexandru C. Telea"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = ""
    facebook = ""

[[menu.main]]
name = "Datasets"
url = "/post/datasets"
weight = 1

[[menu.main]]
name = "Experiment"
url = "/post/experiment"
weight = 2

[[menu.main]]
name = "Measurements"
url = "/post/measurements"
weight = 3

[[menu.main]]
name = "Projections"
url = "/post/projections"
weight = 4
